//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainProject.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email đã tồn tại.
        /// </summary>
        internal static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email sai định dạng.
        /// </summary>
        internal static string EmailInValid {
            get {
                return ResourceManager.GetString("EmailInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập địa chỉ email.
        /// </summary>
        internal static string EmailNotNull {
            get {
                return ResourceManager.GetString("EmailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập user name và mật khẩu.
        /// </summary>
        internal static string NullUserNamePassword {
            get {
                return ResourceManager.GetString("NullUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu chưa khớp.
        /// </summary>
        internal static string PasswordConfirmNotMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập mật khẩu xác nhận.
        /// </summary>
        internal static string PasswordConfirmNotNull {
            get {
                return ResourceManager.GetString("PasswordConfirmNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập mật khẩu.
        /// </summary>
        internal static string PasswordNotNull {
            get {
                return ResourceManager.GetString("PasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string So_dien_thoai_khong_hop_le {
            get {
                return ResourceManager.GetString("So_dien_thoai_khong_hop_le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name không được chứa các ký tự đặc biệt.
        /// </summary>
        internal static string Username_khong_duoc_chua_cac_ky_tu_dac_biet {
            get {
                return ResourceManager.GetString("Username_khong_duoc_chua_cac_ky_tu_dac_biet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name đã tồn tại.
        /// </summary>
        internal static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập user name.
        /// </summary>
        internal static string UserNameNotNull {
            get {
                return ResourceManager.GetString("UserNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được active.
        /// </summary>
        internal static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đúng.
        /// </summary>
        internal static string UserPassIncorrect {
            get {
                return ResourceManager.GetString("UserPassIncorrect", resourceCulture);
            }
        }
    }
}
